@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl DEVICONS/common.puml
!includeurl DEVICONS/devicons2/mysql.puml
!includeurl DEVICONS/devicons2/spring.puml
!includeurl DEVICONS/devicons2/flutter.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Microservices Architecture


System_Boundary(c1, "Apresentação") {
    System(frontend, "Frontend Microservice", "Handles user interface and requests from users.", $sprite="flutter")
}

System_Ext(gateway, "API Gateway", "Handles routing and load balancing.")
System_Ext(firebase, "Firebase", "Handles authentication and authorization.")
ContainerDb(users, "Firebase Users Database", "Stores user data.")

System_Boundary(c2, "Negócio") {
    System(backend1, "Criação Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend2, "Individuos Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend3, "Recintos Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend4, "Especies Serviços", "Handles specific business logic.", $sprite="spring")
    System(backend5, "Importar Plantel Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend6, "Fichas Obitos Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend8, "Reprodução Serviço", "Handles specific business logic.", $sprite="spring")
    System(backend7, "Financeiro Serviço", "Handles specific business logic.", $sprite="spring")
}

System_Boundary(c3, "Persistência") {
    ContainerDb(database, "Database", "Stores data for all microservices.", $sprite="mysql")
}

Rel_D(frontend, gateway, "HTTP Dart Lib")
Rel_R(gateway, firebase,)
Rel_R(firebase, users,)

BiRel_D(gateway, backend1, "Uses", "HTTP")
BiRel_D(gateway, backend2, "Uses", "HTTP")
BiRel_D(gateway, backend3, "Uses", "HTTP")
BiRel_D(gateway, backend4, "Uses", "HTTP")
BiRel_D(gateway, backend5, "Uses", "HTTP")
BiRel_D(gateway, backend6, "Uses", "HTTP")
BiRel_D(gateway, backend7, "Uses", "HTTP")
BiRel_D(gateway, backend8, "Uses", "HTTP")

Rel(backend1, database, "URI", "JDBC")
Rel(backend2, database, "URI", "JDBC")
Rel(backend3, database, "URI", "JDBC")
Rel(backend4, database, "URI", "JDBC")
Rel(backend5, database, "URI", "JDBC")
Rel(backend6, database, "URI", "JDBC")
Rel(backend7, database, "URI", "JDBC")
Rel(backend8, database, "URI", "JDBC")

@enduml