@startuml
' left to right direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl DEVICONS/common.puml
!includeurl DEVICONS/devicons2/mysql.puml
!includeurl DEVICONS/devicons2/spring.puml
!includeurl DEVICONS/devicons2/java.puml
!includeurl DEVICONS/devicons2/flutter.puml
!includeurl DEVICONS/devicons2/dart.puml
!includeurl DEVICONS/devicons2/docker.puml
!includeurl DEVICONS/devicons2/firebase.puml

AddElementTag("v1.1", $fontColor="#000000")

LAYOUT_WITH_LEGEND()

title System Context diagram for Infraestruct Architecture

Component(frontend, "Flutter Microsservice", $techn="Dart", $tags="v1", $descr="Server: Nginx\nPort: 3000", $sprite="docker")


Component(gateway, "API Gateway", $techn="Kong", $descr="Server:Alpine\nPort: 3001\n", $sprite="docker")

Container_Ext(firebase, "Firebase", $descr="URL: https://firebase.google.com\n", $sprite="firebase")

Component(backend, "Java Microservices", $techn="Maven", $descr="Server:Tomcat\nPort: 808X\n", $sprite="docker")
ContainerDb(database, "MySql Database", $descr="URL: http://localhost\nPort: 3306\n", $sprite="docker", $tags="v1.1") 

AddContainerTag("webApp", $sprite="application_server", $legendText="web app container")

Rel_R(frontend, gateway,)
Rel_U(frontend, firebase,)
Rel_R(gateway, backend,)
Rel(backend, database,)
@enduml